language: go

dist: focal

# Remove this if using external Travis
group: focal

go:
- 1.20.x
- 1.21.x

notifications:
  email: true

env:
  global:
    - GO111MODULE=on

before_install:
  - sudo apt-get update
  - pyenv global 3.8
  - sudo apt-get install python
  - npm install -g npm@6.x

install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.55.2
  - curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
  - pip install --user bumpversion
  - npm install @semantic-release/exec
  - npm install @semantic-release/git
script:
  - make travis-ci

# To enable semantic-release, uncomment these sections.
before_deploy:
  - nvm install 18
  - node --version
  - npm --version
  - npm install
  - pip install --user bump2version

deploy:
  - provider: script
    script: npm run semantic-release
    skip_cleanup: true
    on:
      go: '1.20.x' 
      branch: main
