language: go
dist: focal


go:
  - 1.20.x

before_install:
  - sudo apt-get update

install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.51.2
  - curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

script:
  - make travis-ci
  - make tidy
  - make lint

before_deploy:
  - nvm install 14
  - npm install
  - pip install --user bump2version

deploy:
  - provider: script
    script: npm run semantic-release
    skip_cleanup: true
    on:
      go: '1.20.x'
      branch: main